### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by jimcheetham** [nkh/Asciio-2.0#15]
Integration with external tools is often by means of a text file, and it would be nice to be able to automate the generation of a diagram, from the ASCIIO format original directly to the end formats.

So a command-line option to read an ASCIIO input file, and automatically export the text rendering, would be a very useful thing to have

**Comment by nkh** [comment]
Hi,

I read multiple requirements here, I find them interesting but I don't understand them 100%, could you please help clarify?

Integration with external tools is often by means of a text file
- can you please give some examples of tools, or the purpose they would have
- a text file with which contents and what format
- how you would like to see them integrated in your work flow

Able to automate the generation of a diagram, from the ASCIIO format original directly to the end formats.

So a command-line option to read an ASCIIO input file, and automatically export the text rendering, would be a very useful thing to have
- understood: "Option forl asciio to export  the diagram as a text file, without user interaction", as the asciio_to_text command does in the current version, where "text rendering" is one of the 'high formats' you named above

**Comment by jimcheetham** [comment]
I'm using v 1.02.71-1.1 from Ubuntu 16.04.1, and I don't recognise the
"asciio_to_text command". Perhaps my version is too old.

The external tools I am talking about are things like asciitosvg, ditaa,
and so on. They take plain text as an input, not an asciio save file.

My usual workflow:
1 \* Edit a diagram in asciio
2 \* Save it (file.asciio)
3 \* Save as (file.txt)
4 \* Run a2s (asciitosvg) on file.txt to produce file.svg
5 \* Run a2x (asciidoc) on my main documentation file to produce PDF, HTML,
text documents

Steps 4 and 5 are automatic (from a Makefile), based on detecting a new
version of the .txt input file.
I can also detect when the asciio file is written, but my Makefile does not
know how to create the .txt version.

So, if you have an "asciio_to_text" external command already, that will be
enough. That way I can remove step 3 completely, and my documentation will
auto-update when I save the asciio file :-)

-jim

**Comment by nkh** [comment]
I you help me a bit with details about your installation, we may be able to get asciio_to_text to run on your machine. First thing is to head to download this https://github.com/nkh/P5-App-Asciio/blob/master/script/asciio_to_text, cmod +x it, run and tell me what errors it gives you.

I am in contact with the author of a2s, I hope for a tighter integration in the future.

**Comment by jimcheetham** [comment]
It cannot open an X display, because that shell doesn't have any DISPLAY
(and I don't want it to have one).

$ asciio_to_text
Gtk-WARNING **: cannot open display:  at
/usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.

-jim

**Comment by nkh** [comment]
We're out of luck then, at least for a short time.  Xvfb might be a
solution, but there's still the need of GTk libs.

Asciio should not need any thing graphical if no user interaction is
needed. The problem is that asciio_to text is using asciio, the
appllication, not the libraries.

I'll fix this for you, if you don't hear from me in the coming days, ping
me.

N.

**Comment by jimcheetham** [comment]
It is OK to leave this as a v2 issue, I think :-)

**Comment by nkh** [comment]
If the work with Devon goes forward, you may get a "save to SVG" much
sooner than v2.

Actually, we can automate you case without Devon's help! Can you locate
where " /setup/import_export/ascii.pl" is installed?

N

**Comment by jimcheetham** [comment]
/usr/share/perl5/App/Asciio/setup/import_export/ascii.pl

**Comment by nkh** [comment]
Chmod that file so you cn write in it
- locate the line that starts with "write_file($file,"
- there may be commented lines under, just delete them
- add the following line: system "echo $file >> $file.svg" ;
- fire asciio and save a .txt file. You should have a file.txt.svg where
  you saved you .txt file.
- replace echo in the command above by whatever you use to generate the svg
- test/enjoy
- make a backup copy, next version will install over it.

Now come the difficult decision, "leave it there and be happy forever or
fix it properly in 3 mn?"

Fix it !
- Copy your modified export_ascii to export_svg and register it at the top
  of the file
- Remove the modification you made to export_ascii if you do not want a SVG
  to be generated when you generate a txt file
- Do you want the svg generated when you save the .asciio file too?

N.

**Comment by jimcheetham** [comment]
Well yes, except of course you shouldn't be calling the system() function
with unquoted data like that - something as simple as a space in a filename
can spell disaster. But the system call could be correctly quoted easily
enough.

Having a hook would be more flexible - allow users to provide their own
executable/external script to be called, via a fixed-name command.
Something like ~/.asciio/hooks/on-save for example.

I just want a txt file saved whenever I save the asciio file - I'm sure
other people will want the SVG as well, but I already have a bigger
workflow to integrate with (using https://github.com/cortesi/modd to drive
it all)

**Comment by nkh** [comment]
saving to svg, via goat, is implemented in ascio 1.7
