### ISSUE TITLE
Scrollbars for large documents

### ISSUE THREAD

**Issue by nkh** [nkh/Asciio-2.0#18]
optional scroll bars that can be displayed hidden via a shortcut

@yanick, something else? scrolling without scrollbars? zoom out to show all elements? ...

**Comment by yanick** [comment]
The scrollbars are the key feature to deal with a bigger-than-the-window drawing. To be able to zoom out to show all elements is not as critical, but would be nice for sure.

**Comment by nkh** [comment]
I must admit that I am a bit surprised by the need to scroll. I just would like to understand, even though just doing it is simpler ;), if the drawings are so big, printing them becomes a problem; how many characters can you fit in a printed page? 

if you have such big documents, I'd be happy to have one so I understand how uneasy they are to work with.

**Comment by yanick** [comment]
I was finding myself hoping for a bigger canvas when I was drawing things like, say, a database schema. Those can get pretty big much pretty fast. In those cases, worrying about how to print the drawing on paper was not the first priority. To get all the relationships and boxes and arrows on a same document was the main thing, and then after I'd perhaps tidy things up for printing purposes. 

So I guess we are looking at it with two different end-goal in mind. You are perhaps more ascii-art and printing-minded, and I'm more thinking "soft-documents of really huge graphs". :-)

**Comment by nkh** [comment]
I am looking at it with this view, if the user needs it for something and I can help, then I do it.

I think that there is more to big graphs than scrollbar and zooming. For example, If I name an object and scroll away, I may want to jump back to it without having to scroll to find it.

The printing should also be thought of a bit so people can print on multiple pages and glue things together.

Also, maybe we need to define graphs in terms of sub graphs too, so one can work confortably on a sub graph.

I am interested in what kind of interaction one would have.

Have a look at the other requirements, some are a "bit" related.

**Comment by yanick** [comment]
Those would all be awesome additions. I'll go and see the other issues and see if there is anything I can throw my 2 cents at. :-)

**Comment by nkh** [comment]
@yanick implemented in the latest Asciio 1.x series

**Comment by yanick** [comment]
On Fri, 24 Feb 2023, at 5:35 AM, Nadim Khemir wrote:
> @yanick <https://github.com/yanick> implemented in the latest Asciio 1.x series
> 

Woot! Awesome!

**Comment by nkh** [comment]
@yanick let me know how it works for you, specially the upgrade (you need to install perl-gtk3, I did from a package, from CPAN didn't work out)
