### ISSUE TITLE
User-specified stencils

### ISSUE THREAD

**Issue by jimcheetham** [nkh/Asciio-2.0#4]
Allow users to have their own stencil packs, default location in $HOME/.asciio or specified on command-line.
This will require a data format for the stencils, and a mechanism to auto-add them to the menus.

This may be a good way to address nkh/P5-App-Asciio#34 - possibly all stencils can be in the new pack format.

Asciio 1 requires the user to edit the application code in order to add new shapes, and this isn't a good thing.

**Comment by nkh** [comment]
Asciio 1 from version supporting Gtk3 has support for user defined stencils, actions, keyboard bidings, ...
